title: where constant k meets complexity
description: AI for Complex Systems – Climate • Energy • Earth
remote_theme: just-the-docs/just-the-docs
permalink: pretty
markdown: kramdown
plugins:
- jekyll-seo-tag
- jekyll-remote-theme
exclude:
- preview
- UPDATE-NOTES.md
- FIGURE-CREDITS.md
- README.md
- Gemfile
- Gemfile.lock
