title: Dr S. Karthik Mukkavilli
description: AI for Complex Systems - Climate • Energy • Earth
theme: just-the-docs       # <— supports parent/child nav
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-seo-tag         # GitHub Pages whitelists this
