title: Dr ☀️ Karthik Mukkavilli
description: AI • Climate • Energy • Earth Systems
theme: just-the-docs       # <— supports parent/child nav
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-seo-tag         # GitHub Pages whitelists this
