# _config.yml  (Aug 2025)
title: Dr S. Karthik Mukkavilli = k
description: AI for Complex Systems – Climate • Energy • Earth

remote_theme: just-the-docs/just-the-docs  
# theme: just-the-docs                      # (remove this line)

permalink: pretty
markdown: kramdown

plugins:
  - jekyll-seo-tag          
