# _config.yml  (Aug 2025)
title: where constant k meets complexity
description: AI for Complex Systems – Climate • Energy • Earth

remote_theme: just-the-docs/just-the-docs  

permalink: pretty
markdown: kramdown

plugins:
  - jekyll-seo-tag          
